### ISSUE TITLE
No scheduling app found

### ISSUE THREAD

**Issue by fhadeboer** [Darkwater23/MeadMate#90]
Hi and thanks for the awesome app. I thought I would try the add reminder feature but when i click Save it tells me 'no scheduling app found'. Running on stock android 13 here with google caldendar installed.

Let me know if there is anyway i can help debug this. The app doesn't give me much details :)

Yours,

**Comment by Darkwater23** [comment]
Interesting! I'll do some research and see if the Google Calendar is registered with Android another way.

**Comment by Darkwater23** [comment]
I think I found the solution already. I need to explicitly declare that I'm going to use this action/intent in the app manifest. I am able to recreate the problem on my devices, so I should be able to fix this quickly.

**Comment by Darkwater23** [comment]
I tested the "Add Reminder" feature in my Pixel 3a emulator and was able to recreate the issue. I added the required XML to the Android app manifest to allow the feature to work. The "Add Reminder" feature started working again. Pushed fix to PROD.

**Comment by fhadeboer** [comment]
Awesome. Thanks
